language: ruby
rvm:
  - 2.1.0
script: bundle exec jekyll build
cache:
  bundler: true
deploy:
  provider: divshot
  skip_cleanup: true
  edge: true
  environment:
    master: development
    staging: staging
    production: production