name: Static Apps
markdown: redcarpet
pygments: true
exclude:
  - Gemfile
  - divshot.json
  - .bowerrc
  - .travis.yml
  - Gemfile.lock
assets:
  sources:
    - _assets/images
    - _assets/stylesheets
    - _assets/javascripts
    - _bower